version: '3.8'

services:

 db: #same as MYSQL_NAME
  image: mariadb:latest
  restart: always
  ports:
   - $EXTERNAL_SQL_PORT:3306
  environment:
   MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
   MYSQL_USER: $MYSQL_USER
   MYSQL_PASSWORD: $MYSQL_PASSWORD
   MYSQL_DATABASE: $MYSQL_DATABASE
   EXTERNAL_SQL_PORT: $EXTERNAL_SQL_PORT
  volumes:
   - "./scripts/table1.sql:/docker-entrypoint-initdb.d/1.sql"

 webserver:
  build:
   context: ./php
   dockerfile: dockerfile
  depends_on:
   - db
  links:
   - db
  environment:
   MYSQL_NAME: $MYSQL_NAME
   MYSQL_USER: $MYSQL_USER
   MYSQL_PASSWORD: $MYSQL_PASSWORD
   MYSQL_DATABASE: $MYSQL_DATABASE
   EXTERNAL_SQL_PORT: $EXTERNAL_SQL_PORT
   VIRTUAL_HOST: $HOST

 proxy:
  image: jwilder/nginx-proxy
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock:ro
  ports:
   - 80:80
   - 443:443
  links:
   - webserver
  environment:
   DEFAULT_HOST: $HOST

 phpmyadmin:
  image: phpmyadmin:latest
  links:
   - db
  depends_on:
   - db
  ports:
   - $EXTERNAL_PMA_PORT:80
  environment:
   PMA_PORT: $EXTERNAL_SQL_PORT
   PMA_ARBITRARY: 1
